package com.keepalive.yesplus

import android.net.wifi.WifiManager
import android.os.Handler
import android.os.Looper
import android.util.Log

/**
 * Manages WiFi Hotspot for the app.
 * Uses the public WifiManager.startLocalOnlyHotspot() API.
 *
 * Note: The SSID and password are auto-generated by the system.
 * For custom SSID/password, use the hotspot.command script via ADB.
 */
class HotspotManager(private val wifiManager: WifiManager) {

    companion object {
        private const val TAG = "YesPlusHotspot"
    }

    private var hotspotReservation: WifiManager.LocalOnlyHotspotReservation? = null
    var isHotspotActive = false
        private set

    // Store the active hotspot credentials
    var activeSsid: String = ""
        private set
    var activePassword: String = ""
        private set

    var onHotspotStarted: ((ssid: String, password: String) -> Unit)? = null
    var onHotspotStopped: (() -> Unit)? = null
    var onHotspotFailed: ((reason: String) -> Unit)? = null

    /**
     * Start the hotspot. SSID and password are auto-generated by the system.
     */
    fun startHotspot() {
        if (isHotspotActive) {
            onHotspotFailed?.invoke("Hotspot כבר פעיל")
            return
        }

        try {
            wifiManager.startLocalOnlyHotspot(object : WifiManager.LocalOnlyHotspotCallback() {
                override fun onStarted(reservation: WifiManager.LocalOnlyHotspotReservation?) {
                    hotspotReservation = reservation
                    isHotspotActive = true

                    // Get credentials from the reservation
                    @Suppress("DEPRECATION")
                    val config = reservation?.wifiConfiguration
                    activeSsid = config?.SSID ?: "Unknown"
                    activePassword = config?.preSharedKey ?: "Unknown"

                    // Try to get from SoftApConfiguration on API 30+
                    try {
                        val softApConfig = reservation?.softApConfiguration
                        if (softApConfig != null) {
                            activeSsid = softApConfig.ssid ?: activeSsid
                            activePassword = softApConfig.passphrase ?: activePassword
                        }
                    } catch (e: Exception) {
                        // Ignore - use WifiConfiguration values
                    }

                    Log.i(TAG, "Hotspot started! SSID: $activeSsid")
                    onHotspotStarted?.invoke(activeSsid, activePassword)
                }

                override fun onStopped() {
                    cleanup()
                    onHotspotStopped?.invoke()
                }

                override fun onFailed(reason: Int) {
                    isHotspotActive = false
                    val reasonStr = when (reason) {
                        ERROR_NO_CHANNEL -> "אין ערוץ זמין"
                        ERROR_GENERIC -> "שגיאה כללית"
                        ERROR_INCOMPATIBLE_MODE -> "מצב לא תואם — נסה לכבות WiFi קודם"
                        ERROR_TETHERING_DISALLOWED -> "Tethering לא מורשה"
                        else -> "שגיאה לא ידועה ($reason)"
                    }
                    Log.e(TAG, "Hotspot failed: $reasonStr")
                    onHotspotFailed?.invoke(reasonStr)
                }
            }, Handler(Looper.getMainLooper()))

        } catch (e: SecurityException) {
            Log.e(TAG, "Permission denied: ${e.message}")
            onHotspotFailed?.invoke("חסרות הרשאות — הרץ את המתקין כדי לתת הרשאות")
        } catch (e: Exception) {
            Log.e(TAG, "Error starting hotspot: ${e.message}", e)
            onHotspotFailed?.invoke(e.message ?: "שגיאה לא ידועה")
        }
    }

    /**
     * Stop the hotspot.
     */
    fun stopHotspot() {
        try {
            hotspotReservation?.close()
            cleanup()
            Log.i(TAG, "Hotspot stopped by user")
            onHotspotStopped?.invoke()
        } catch (e: Exception) {
            Log.e(TAG, "Error stopping hotspot: ${e.message}")
        }
    }

    private fun cleanup() {
        hotspotReservation = null
        isHotspotActive = false
        activeSsid = ""
        activePassword = ""
    }
}
